Vytvoření jednotného stylu
VUT-FEKT-IBE/FEKT.tex pull request #1
Opened 2021-12-28 14:12 UTC by kamen-u-cesty

Synchronizace s aktualizovaným stylem státnicových otázek.

2021-12-28 23:43 UTC, czechbol requested changes
Vypadá to dobře, ale...

- chce to buď aktualizovat přiložené PDF, nebo ho smazat a přidat GH Actions skript co buildne PDF při novém commitu a adekvátně to popsat v `README`.
- popřemýšlel bych nad `.gitignore` templatem. Používám je často a jsou super protože bez ohledu na to co člověk začne dělat, tak to prostě funguje. Beru je přes oh-my-zsh plugin, ale template je dostupný z webu. (pro LaTeX [zde](https://www.toptal.com/developers/gitignore/api/latex))

Jinak mě momentálně nic nenapadá.

2021-12-29 08:29 UTC, kamen-u-cesty commented
- Ukázku bych radši generoval přes Actions a v README ji linkovat, nemuseli bychom commitovat binární blob kdykoliv uděláme vizuální změnu.
- `.gitignore` template přidat můžeme.

2021-12-29 12:30 UTC, jedla97 reviewed
Osobně s čím mám největší problém je asi využití `minted` balíčku. Pokud by to někdo chtěl dělat lokálně tak musí mít nainstalovaný python, `pygments` a spouštět kompilaci s argumentem `-shell-escape`. Nevím jak je to na Linuxu, ale s tímhle problémem jsem se setkal na Windows. 
Z mého pohledu jsou 3 možnosti

1.  Odstranění
2.  Doplnění tohoto do README
3.  Doplnění do README že pokud uživatel nechce používat minted tak ať si zakomentářuje řádky 155 -157 v `shared.tex`

Pro toto bych vzal v potaz, že windows nemá v základu nainstalovaný python.
Postup je například [zde](https://newbedev.com/how-to-use-minted-under-miktex-and-windows-7) je to pro python2 ale na python 3 je postup stejný.


K té ukázce souhlasím, že je lepší to generovat pomocí GH actions. Ty můžu upravit na tohle repo z těch státnicových.

2021-12-29 15:57 UTC, czechbol commented on shared.tex
> +    \usemintedstyle{pastie}
tento řádek určuje color scheme ne formátování

Viz:
https://cs.overleaf.com/learn/latex/Code_Highlighting_with_minted#Reference_guide

2021-12-29 16:03 UTC, kamen-u-cesty commented on shared.tex
> +    \usemintedstyle{pastie}
Fixed & force-pushed

2021-12-29 16:04 UTC, czechbol approved these changes
LGTM

2021-12-29 20:37 UTC, jedla97 approved these changes

2021-12-29 20:39 UTC, merged